### PR TITLE
Add system font

### LINKED ISSUE #3: Update typography settings
Update the typography settings so that they match the [desktop](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020042%3A412) and [mobile](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020042%3A427) designs. Example PRs [here](https://github.com/Automattic/themes/pull/6479), [here](https://github.com/Automattic/themes/pull/6487) and [here](https://github.com/Automattic/themes/pull/6571).

## Desktop
Screen Shot 2022-09-30 at 3 12 13 PM

## Mobile
Screen Shot 2022-09-30 at 3 12 40 PM

#### Scenario: Typography settings
**Given** The Sensei theme is activated
**When** I view a page containing `h1` - `h4` headings and paragraph blocks
**Then** the typography looks similar to the design on both desktop and mobile.

### PR DESCRIPTION
**Pull request by gabrielcaires**
## Introduced changes
- Remove .DS_Store file
- Add DS_Store to gitignore
- Add the "System" font option on the theme, to be used on elements that are using the SF pro.

Screen Shot 2022-10-05 at 16 02 32

#### Block Editor
- Create a page
- Add a post date
```
<!-- wp:post-date /-->
```
Check if the post date is using the introduced font.

### Site editor
Go to the Site Editor 
* Open the Styles tab
* Check if the System font options is available.
Screen Shot 2022-10-05 at 15 58 36

### CODE REVIEW

**Comment by gabrielcaires** [comment]
@Luchadores I am using the SF Pro (-apple-system and BlinkMacSystemFont) here, but it is only available on macOS.
The other fallback fonts are:
Segoe UI 
"Roboto"
"Oxygen-Sans"
"Ubuntu"
"Cantarell"
"Helvetica Neue"
'sans-serif"

**Review by LavaGolem — DISMISSED** [review]
Looks good

**Comment by Luchadores** [comment]
I just to make sure this wasn't lost in Slack. If we can keep SF Pro, that is great, if not I've prepared the Inter alternative which is ready to go.

If we go with the list @gabrielcaires proposed for fallbacks, I would add Inter as a second fallback font. [Google link](https://fonts.google.com/specimen/Inter?query=inter).

image

**Comment by gabrielcaires** [comment]
> I just to make sure this wasn't lost in Slack. If we can keep SF Pro, that is great, if not I've prepared the Inter alternative which is ready to go.

I added the Inter font as a fallback, so we have:

SF (only for mac users), Inter (download on our theme),  Segoe UI, Roboto, Oxygen-Sans, Ubuntu, Cantarell, Helvetica Neue, sans-serif;

Is it ok now @Luchadores ?

**Comment by Luchadores** [comment]
Nice, thank you @gabrielcaires! 🙌

**Review by Imran92 — APPROVED** [review]

**Pull request merged**
