### PR TITLE
Style the comment thread and reply form to look closer to design

### LINKED ISSUE #6: Update comments styles
Update the comments and comment reply form to match the [desktop](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020065%3A1078) and [mobile](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020126%3A4278) designs. Example PR [here](https://github.com/Automattic/themes/pull/6520).

Note that we likely won't be able to customize all of the styles using `theme.json`, so we'll need to use custom CSS for some of it.

## Desktop
Screen Shot 2022-09-28 at 4 18 18 PM

## Mobile
Screen Shot 2022-09-30 at 4 08 01 PM

#### Scenario: Comments & comment reply form
**Given** I've enabled comments for a post
**And** I've added multiple comments for the post, including nested comments
**When** I view the post on the frontend
**Then** the comments and comment reply form look similar to the design on both desktop and mobile.

### PR DESCRIPTION
**Pull request by Imran92**
Implements https://github.com/Automattic/sensei-theme/issues/6

### Changes proposed
Changes the following to match the design

- Comment reply form input sizes, borders and orders of all input fields

- Form input fields structure in desktop and mobile
- All label and description font sizes
- Background color for input elements
- Button font sizes
- URL designs
- Author title font and spacing
- Author avatar spacing and border setting
- Comment reply date spacing and position
- Comment reply body spacing and position
- Edit link
- Reply link
- Reply text and Reply cancel button
- Spacing between the reply threads and inner elements
- Alignment of avatar, title and content elements

### Testing instruction

- Add a post
- Allow commenting to that post
- Go to the frontend and add a couple of comments and replies
- Make sure they look similar to the design

### Screenshot
Desktop
image

Mobile
image

### CODE REVIEW

**Comment by LavaGolem** [comment]
The comments section looks off to me, I will check with someone else to see if it is me :D 

image


image

**Comment by LavaGolem** [comment]
1. Links

@Imran92  so I've noticed that the links (Like :Edit, reply) in the design have underlined text decoration, this is actually fixed in new changes since there are some conflicts with **theme.json** can you resolve them first? 

Here is how comments look to me: 
image

2. In the design it is not just a author name, but name  + says: (I'm not sure we really want it and how complicated it is to add it)
image

3. Everything is the same font size in the design, while in this PR date and author name are smaller.

image

4. There is a comment header in the comments block: 
image

**Comment by Imran92** [comment]
Thanks for the review @LavaGolem, I've merged the trunk and [added some changes](https://github.com/Automattic/sensei-theme/pull/35/commits/4d30819c92c52a0d884f710dbb4da482771c56c0) too. Can you kindly take a look again?

1. The links should be alright now and have the as the design
2. It requires content manipulation, I'm sure we should change the block's default contents
3. It was related to having Gutenberg plugin installed, can you kindly recheck?
4. This is actually generated from the Comments Title block, I've changed the style a bit and removed the comment count and post heading. But changing to "Comments" from "Responses" requires content change. So kept the default block behavior.

Thanks!

**Review by gabrielcaires — APPROVED** [review]
I tested the scenarios and it looks fines

**Pull request merged**
