### PR TITLE
Set wide template as default for courses

### PR DESCRIPTION
**Pull request by gabrielcaires**
Fix issue [Add a template for the post type "Course"#6091](https://github.com/Automattic/sensei/issues/6091)

### Introduced change
- Set the wide template as default for courses

### Testing instructions
- Create a course
- Check if the template was selected by default.

Screenshot 2022-11-22 at 18 34 04

### CODE REVIEW

**Comment by donnapep** [comment]
I think we'll need two templates here:

- A full width one without the title (pages)
- A full width one with the title (courses)

**Comment by gabrielcaires** [comment]
> I think we'll need two templates here:
> 
> * A full width one without the title (pages)
> * A full width one with the title (courses)

@donnapep I am a bit confused because our course pattern is implementing custom titles, so they should not have titles.

Are you suggesting creating another template wide with a title that can be applied to courses and any other post type?
The template implemented here is available for all post types, there is no restriction, so I think we are only missing another one which is Wide+Title.

Is it that you meant?

**Comment by donnapep** [comment]
> I am a bit confused because our course pattern is implementing custom titles, so they should not have titles.

Not everyone will use the pattern though. If we set the course to use this template by default, but the user doesn't add the pattern, then their course page will not display the title, which isn't good.

I believe the point of adding the new template in the first place is to ensure that we can utilize the full width of the page for the course landing pattern. And we thought we should set it as the default template because otherwise it would be tricky to detect when the pattern is added to the page, so that we know to update the page template that is being used (which probably isn't a good idea anyway).

It sounds like we have a bit of a dilemma here:
- If we set the default course template to not display the title, then new courses that DON'T add the pattern won't have a title.
- If we set the default course template to display the title, then new courses that DO add the pattern will have the title duplicated.

Do you think we should consider naming the template "Wide Width", and hiding the title via CSS or something if the landing page pattern has been added? Not sure how feasible that is.

Tagging @Imran92 too as he created the original issue

**Comment by Imran92** [comment]
> I believe the point of adding the new template in the first place is to ensure that we can utilize the full width of the page for the course landing pattern

You're totally right. That was the main reason. Because the template for a single post was 2 column one and that's not how we want our courses to look.

> If we set the default course template to display the title

I think we should, because that's how all Courses look now. Having a title should be the default behavior I believe. Using the pattern is the exceptional or less used scenario here.

> Do you think we should consider naming the template "Wide Width"

I'm not sure about this, if we name this not following [this convention](https://developer.wordpress.org/themes/template-files-section/custom-post-type-template-files/#custom-post-type-templates), we'll have to check whether it behaves as expected and overrides the default `single.html` template

> hiding the title via CSS or something if the landing page pattern has been added? Not sure how feasible that is.

Yeah I'm not sure too. Can think right away about achieving it with JS, but not how to do it with CSS

**Comment by gabrielcaires** [comment]
@donnapep @Imran92 
I think the trick part is try to keep the course title in a pattern, maybe we should not try to do it, so instead of we can provide multiples templates with title variation like (Regular, Cover, etc...).


What do you think about the idea:
Template 1: Wide  + Regular Title
Template 2: Wide + Cover Title  (Title with the Green background + Image) << Set it as default 
Template 3:  Regular Title (No Wide)

What do you think?

**Comment by donnapep** [comment]
We decided to have 4 templates as outlined in https://github.com/Automattic/course/issues/125.

**Pull request closed without merging**
